CLASSES: dict[str, str] = {
    "h1": "display-4 mb-4",
    "h2": "display-5 mb-3",
    "h3": "display-6 mb-3",
    "h4": "h4 mb-3",
    "h5": "h5 mb-2",
    "h6": "h6 mb-2",
    "p": "mb-3",
    "a": "text-primary text-decoration-none",
    "img": "img-fluid rounded",
    "blockquote": "blockquote",
    "blockquote_footer": "blockquote-footer text-muted",
    "code_inline": "text-monospace bg-light px-1 rounded",
    "pre": "highlight mb-3",
    "table": "table table-striped table-hover",
    "thead": "table-light",
    "th": "text-nowrap",
    "hr": "my-4",
    "ul": "list-unstyled ps-3",
    "ol": "list-unstyled ps-3",
    "li": "mb-1",
    "task_list_item": "task-list-item",
    "task_list_checkbox": "form-check-input me-1",
    "task_list_label": "form-check-label",
    "footnote_ref": "badge bg-secondary",
    "footnote_block": "footnotes mt-4 border-top pt-3",
}
